/*
 * generated by Xtext 2.20.0
 */
package org.xtext.jvs.validation

import org.xtext.jvs.asso.Variable
import org.eclipse.xtext.validation.Check
import org.xtext.jvs.asso.VariableRef
import org.xtext.jvs.asso.AssoPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class AssoValidator extends AbstractAssoValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					AssoPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
