/*
 * generated by Xtext 2.20.0
 */
package org.xtext.jvs.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.jvs.AssoRuntimeModule
import org.xtext.jvs.AssoStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class AssoIdeSetup extends AssoStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new AssoRuntimeModule, new AssoIdeModule))
	}
	
}
