/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.jvs


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EntitiesRuntimeModule extends AbstractEntitiesRuntimeModule {
}
