/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.jvs


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EntitiesStandaloneSetup extends EntitiesStandaloneSetupGenerated {

	def static void doSetup() {
		new EntitiesStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
