grammar org.xtext.jvs.Math with org.eclipse.xtext.common.Terminals

generate math "http://www.xtext.org/jvs/Math"

Model: math=MathExp;

MathExp:
	'result' 'is' exp=Exp
;

Exp: // Illegal due to left recursion
	left=Primary (operator=ExpOp right=Exp)?
;


ExpOp:
	{Plus} '+' | {Minus} '-'	 | {Mult} '*' | {Div} '/'	
;

Primary:
	Number | Parenthesis
;

Parenthesis:
	'(' exp=Exp ')'
;

Number:
	value=INT
;