/*
 * generated by Xtext 2.20.0
 */
package org.xtext.jvs


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MathStandaloneSetup extends MathStandaloneSetupGenerated {

	def static void doSetup() {
		new MathStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
